# Generated by Django 5.1.7 on 2025-03-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S3ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('read', 'Чтение'), ('upload', 'Загрузка'), ('download', 'Скачивание'), ('delete', 'Удаление'), ('create_folder', 'Создание папки'), ('delete_folder', 'Удаление папки')], max_length=20, verbose_name='Тип действия')),
                ('object_path', models.CharField(max_length=255, verbose_name='Путь к объекту в S3')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=255, verbose_name='Путь к папке в S3')),
                ('can_read', models.BooleanField(default=True, verbose_name='Может читать')),
                ('can_write', models.BooleanField(default=False, verbose_name='Может записывать')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Может удалять')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'unique_together': {('user', 'folder_path')},
            },
        ),
    ]
